services:
  mysql:
    image: mysql:8.0
    container_name: easyhotel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easyhotel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  mysql-data:
    driver: local