-- AlterTable
ALTER TABLE `hotel` ADD COLUMN `hasFreeWifi` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasGym` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasParking` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasTV` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `room` ADD COLUMN `roomType` INTEGER NOT NULL DEFAULT 1;
