export const ROOM_FACILITY_FIELDS = [
  "cleaningFacilities",
  "bathingFacilities",
  "layoutFacilities",
  "accessibleFacilities",
  "networkFacilities",
  "bathroomFacilities",
  "foodFacilities",
  "childFacilities",
  "mediaFacilities",
  "roomSpecFacilities",
  "kitchenFacilities",
  "amenityFacilities",
  "viewFacilities",
] as const;

export type RoomFacilityField = (typeof ROOM_FACILITY_FIELDS)[number];

export const HOTEL_DB_TAGS = [
  "BUFFET_BREAKFAST",
  "BUTLER_SERVICE",
  "CHARGING_PILE",
  "CHESS_ROOM",
  "CINEMA_ROOM",
  "COFFEE_MACHINE",
  "DELIVERY_ROBOT",
  "DRYER",
  "FAMILY_ROOM",
  "FREE_LAUNDRY",
  "FREE_LUGGAGE",
  "FREE_PARKING",
  "FREE_WIFI",
  "GYM",
  "HEATING",
  "INSTAGRAMMABLE",
  "KTV",
  "LAUNDRY_ROOM",
  "MEETING_HALL",
  "MEMBER_BENEFITS",
  "NON_SMOKING_FLOOR",
  "ROBOT_SERVICE",
  "SELF_CHECKIN",
  "SMART_CONTROL",
  "SUITE",
  "VINTAGE_STYLE",
] as const;

export type HotelDbTag = (typeof HOTEL_DB_TAGS)[number];

export const HOTEL_CN_TO_DB_TAG_MAP: Record<string, HotelDbTag[]> = {
  免费WiFi: ["FREE_WIFI"],
  免费WIFI: ["FREE_WIFI"],
  健身房: ["GYM"],
  免费停车: ["FREE_PARKING"],
  充电桩: ["CHARGING_PILE"],
  洗衣房: ["LAUNDRY_ROOM", "FREE_LAUNDRY"],
  免费洗衣: ["FREE_LAUNDRY"],
  机器人服务: ["ROBOT_SERVICE", "DELIVERY_ROBOT"],
  送物机器人: ["DELIVERY_ROBOT"],
  会议厅: ["MEETING_HALL"],
  家庭房: ["FAMILY_ROOM"],
  套房: ["SUITE"],
  行李寄存: ["FREE_LUGGAGE"],
  自助入住: ["SELF_CHECKIN"],
  无烟楼层: ["NON_SMOKING_FLOOR"],
  暖气: ["HEATING"],
  咖啡机: ["COFFEE_MACHINE"],
  烘干机: ["DRYER"],
  复古风: ["VINTAGE_STYLE"],
  网红打卡: ["INSTAGRAMMABLE"],
  KTV: ["KTV"],
  棋牌室: ["CHESS_ROOM"],
  影院房: ["CINEMA_ROOM"],
  自助早餐: ["BUFFET_BREAKFAST"],
  智能客控: ["SMART_CONTROL"],
  会员权益: ["MEMBER_BENEFITS"],
  管家服务: ["BUTLER_SERVICE"],
};

export const ROOM_TAG_VALUE_MAP = {
  areaTitles: {
    小于35: "less35",
    "20-25m2": "less35",
    "25-30m2": "less35",
    "35-50": "35-50",
    "50以上": "50above",
    "50m2+": "50above",
    "30m2+": "35-50",
  },
  bedTitles: {
    单人床: "single",
    双床: "twin",
    双人床: "double",
    大床: "king",
    其他: "others",
  },
  window: {
    有: "y",
    无: "n",
    y: "y",
    n: "n",
  },
  smoke: {
    可吸烟: "y",
    禁烟: "n",
    y: "y",
    n: "n",
  },
  wifi: {
    有: "y",
    无: "n",
    y: "y",
    n: "n",
  },
} as const;

export const ROOM_DB_TAGS_BY_FIELD: Record<RoomFacilityField, string[]> = {
  cleaningFacilities: ["DAILY_CLEANING", "CLEANING_TOOLS", "IRONING"],
  bathingFacilities: [
    "BATHTUB",
    "RAIN_SHOWER",
    "SHOWER",
    "BATHROBE",
    "BATH_TOWEL",
    "TOWEL",
  ],
  layoutFacilities: [
    "DESK",
    "SOFA",
    "WARDROBE",
    "LOUNGE_CHAIR",
    "COFFEE_TABLE",
    "DECORATIVE_PAINTING",
  ],
  accessibleFacilities: ["BATHTUB_HANDRAILS", "DOORBELL_PROMPT"],
  networkFacilities: ["ROOM_WIFI", "TELEPHONE", "INT_CALL"],
  bathroomFacilities: [
    "PRIVATE_BATHROOM",
    "PRIVATE_TOILET",
    "SMART_TOILET",
    "HAIR_DRYER",
    "MIRROR",
    "HOT_WATER_24H",
    "SLIPPERS",
  ],
  foodFacilities: [
    "MINI_BAR",
    "SOFT_DRINK",
    "TEA_BAGS",
    "WATER",
    "FRUIT",
    "ALCOHOL",
    "KETTLE",
  ],
  childFacilities: ["CRIB", "TOYS", "TOILET_SEAT"],
  mediaFacilities: ["LCD_TV", "CABLE", "SMART_LOCK", "SMART_CONTROL"],
  roomSpecFacilities: [
    "AC",
    "AUTO_CURTAINS",
    "BLACKOUT_CURTAINS",
    "AIR_PURIFIER",
    "EXTRA_LONG_BED",
    "DUCK_DOWN",
    "BLANKET",
    "SPARE_BEDDING",
    "HANGERS",
    "SOCKET_MULTI",
    "SAFE_BOX",
    "SCALE",
    "SEWING_KIT",
    "TURN_DOWN",
    "UMBRELLA",
    "VOLTAGE_110V",
    "VOLTAGE_220V",
    "WELCOME_GIFT",
    "BUTLER",
  ],
  kitchenFacilities: ["REFRIGERATOR"],
  amenityFacilities: [
    "TOOTHBRUSH",
    "TOOTHPASTE",
    "SHOWER_GEL",
    "SHAMPOO",
    "CONDITIONER",
    "SOAP",
    "SHOWER_CAP",
    "COMB",
    "RAZOR",
    "TOILETRIES",
  ],
  viewFacilities: ["CITY_VIEW", "LANDMARK_VIEW", "RIVER_VIEW"],
};

export const ROOM_CN_TO_DB_TAG_MAP: Record<string, Partial<Record<RoomFacilityField, string[]>>> = {
  浴缸: { bathingFacilities: ["BATHTUB"] },
  淋浴: { bathingFacilities: ["SHOWER", "RAIN_SHOWER"] },
  吹风机: { bathroomFacilities: ["HAIR_DRYER"] },
  独立卫浴: { bathroomFacilities: ["PRIVATE_BATHROOM"] },
  智能马桶: { bathroomFacilities: ["SMART_TOILET"] },
  书桌: { layoutFacilities: ["DESK"] },
  沙发: { layoutFacilities: ["SOFA"] },
  衣柜: { layoutFacilities: ["WARDROBE"] },
  无障碍设施: { accessibleFacilities: ["BATHTUB_HANDRAILS", "DOORBELL_PROMPT"] },
  房间WiFi: { networkFacilities: ["ROOM_WIFI"] },
  电视: { mediaFacilities: ["LCD_TV", "CABLE"] },
  智能控制: { mediaFacilities: ["SMART_CONTROL"], roomSpecFacilities: ["SMART_CONTROL"] },
  迷你吧: { foodFacilities: ["MINI_BAR"] },
  冰箱: { kitchenFacilities: ["REFRIGERATOR"] },
  儿童床: { childFacilities: ["CRIB"] },
  清洁服务: { cleaningFacilities: ["DAILY_CLEANING", "CLEANING_TOOLS"] },
  熨烫: { cleaningFacilities: ["IRONING"] },
  城景: { viewFacilities: ["CITY_VIEW"] },
  江景: { viewFacilities: ["RIVER_VIEW"] },
  地标景观: { viewFacilities: ["LANDMARK_VIEW"] },
};
